name: Compile Sing-Box Rules

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
permissions:
  contents: write

env:
  SING_BOX_VERSION: 1.10.0-beta.4

jobs:
  sync_and_compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      
    # - name: Set up Git user
    #   run: |
    #     git config user.name "github-actions[bot]"
    #     git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install sing-box
      run: |
        curl -Lo sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v${SING_BOX_VERSION}/sing-box-${SING_BOX_VERSION}-linux-amd64.tar.gz
        tar -xzf sing-box.tar.gz
        chmod +x sing-box-${SING_BOX_VERSION}-linux-amd64/sing-box
        sudo mv sing-box-${SING_BOX_VERSION}-linux-amd64/sing-box /usr/local/bin/sing-box
        sing-box version
        
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 15
      with:
        sudo: false

    - name: Compile Sing-Box Rules
      run: |
        rm -rf sing-box/rules_srs/*
        for file in sing-box/rules_json/*.json; do
          filename=$(basename "$file" .json)
          sing-box rule-set compile "$file" -o "sing-box/rules_srs/${filename}.compiled"
        done
    
    - name: Commit compiled rules
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add sing-box/rules_srs/*
        git commit -m "Compiled rules from JSON files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}